spring:
  application:
    name: config-server-ha
  cloud:
    config:
      server:
        git:
          uri: https://github.com/andyChenHuaYing/spring-cloud-demo
          searchPaths: config-repository
          username:
          password:
          forcePull: true
      label: dev-20180827

server:
  port: 8772

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/