spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/andyChenHuaYing/spring-cloud-demo
          searchPaths: config-repository
          username:
          password:
      label: dev-20180827

server:
  port: 8769

